### ISSUE TITLE
xml config can't render properly in AS design

### ISSUE THREAD

**Issue by Ernest-su** [cctanfujun/ProgressRoundButton#8]
```
java.lang.NullPointerException
	at com.xiaochen.progressroundbutton.AnimDownloadProgressButton.drawableStateChanged(AnimDownloadProgressButton.java:117)
	at android.view.View.refreshDrawableState(View.java:17919)
	at android.view.View.dispatchAttachedToWindow(View.java:15424)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:333)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by GoodmanLi** [comment]
这个错还在啊，解决了吗
